version: '3.9'

services:
  web:
    image: node:18
    container_name: keys_web
    working_dir: /app
    volumes:
      - ${WEB_PATH}:/app
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keys.rule=Host(`${FULL_DOMAIN}`)"
      - "traefik.http.routers.keys.entrypoints=websecure"
      - "traefik.http.routers.keys.tls.certresolver=letsencrypt"
      - "traefik.http.services.keys.loadbalancer.server.port=${APP_PORT}"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
