version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keys_web
    working_dir: /app
    environment:
      NODE_ENV: production
    networks:
      - traefik
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.keys.rule: "Host(`${FULL_DOMAIN}`)"
      traefik.http.routers.keys.entrypoints: websecure
      traefik.http.routers.keys.tls.certresolver: letsencrypt
      traefik.http.services.keys.loadbalancer.server.port: "${APP_PORT}"

  webhook:
    build:
      context: ./webhook-server
    container_name: keys_webhook
    working_dir: /app
    volumes:
      - ./webhook-server:/app
      - ./deploy.sh:/projects/keys/deploy.sh:ro
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
